export const PLAN_CREATED_SUCESSFULLY = 'Plan created successfully!!';
export const INVALID_PLAN = 'Invalid plan! Plan not found.';
export const INVALID_REQUEST = 'Invalid request';
export const PROMOTION_CREATED_SUCESSFULLY = 'Promotion created successfully!!';
export const USER_ENROLLMENT_SUCCESSFULL = 'User enrolled successfully';
export const CUSTOMER_ADDED_SUCCESSFULL = 'Customer added successfully';
export const INVALID_PROMOTION = 'Invalid promotion';
export const EXPIRED_PROMOTION = 'Expired promotion';
export const LOW_BALANCE = 'Low balance! Amount deposited is insufficient';