export const BENEFIT_TYPE = {
    NONE: 'NONE',
    CASHBACK: 'CASHBACK',
    EXTRA_VOUCHER: 'EXTRA_VOUCHER',
};
export const PROMOTION_TYPE = {
    NONE: 'NONE',
    LIMIT_BY_USERS: 'USER_LIMIT',
    LIMIT_BY_PERIOD: 'TIME_LIMIT',
};